version: "3.8"

services:
  frontend:
    build: ./frontend
    container_name: mern-frontend
    ports:
      - "3000:80"  # Map host port 3000 to container port 80 (Nginx)
    depends_on:
      - backend
    
  backend:
    build: ./backend
    container_name: mern-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/mernDB
    depends_on:
      - mongo
    
  mongo:
    image: mongo:6.0
    container_name: mern-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: